# Generated by Django 4.2.17 on 2024-12-19 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('unidade_medida', models.IntegerField(choices=[(0, 'KILO'), (1, 'LITRO'), (2, 'GRAMA'), (3, 'ML')])),
                ('quantidade', models.IntegerField()),
                ('data_validade', models.DateField()),
                ('custo_unitario', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.IntegerField(choices=[(0, 'DISPONIVEL'), (1, 'INDISPONIVEL')], default=0)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=5)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Pratos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.IntegerField(choices=[(0, 'DISPONIVEL'), (1, 'INDISPONIVEL')], default=0)),
                ('acompanhamento', models.ManyToManyField(to='orders.acompanhamentos')),
            ],
        ),
        migrations.CreateModel(
            name='MovimentacaoProdutos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.IntegerField(choices=[(0, 'ENTRADA'), (1, 'SAIDA')])),
                ('quantidade', models.IntegerField()),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.produtos')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPratos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantidade_por_porcao', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.pratos')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.produtos')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoCustoProdutos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data', models.DateField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.produtos')),
            ],
        ),
    ]
