# Generated by Django 4.2.17 on 2024-12-23 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_pratos_acompanhamento_delete_itempratos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoprodutos',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.produtos'),
        ),
        migrations.AlterField(
            model_name='movimentacaoprodutos',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'ENTRADA'), (1, 'SAIDA'), (2, 'CORRECAO'), (3, 'EXCLUIDO')]),
        ),
    ]
