# Generated by Django 4.2.17 on 2024-12-19 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0002_remove_pratos_acompanhamento_delete_itempratos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pratos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.IntegerField(choices=[(0, 'DISPONIVEL'), (1, 'INDISPONIVEL')], default=0)),
                ('acompanhamento', models.ManyToManyField(to='orders.acompanhamentos')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPratos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantidade_por_porcao', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishes.pratos')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.produtos')),
            ],
        ),
    ]
