# Generated by Django 4.2.17 on 2024-12-28 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0004_remove_itempratos_prato_remove_itempratos_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempratos',
            name='prato',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='dishes.pratos'),
        ),
    ]
