# Generated by Django 4.2.17 on 2024-12-28 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_produtos_unidade_medida'),
        ('dishes', '0005_alter_itempratos_prato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempratos',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.produtos'),
        ),
    ]
