# Generated by Django 4.2.17 on 2025-01-03 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_produtos_unidade_medida'),
        ('dishes', '0006_alter_itempratos_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempratos',
            name='prato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishes.pratos'),
        ),
        migrations.AlterField(
            model_name='itempratos',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.produtos'),
        ),
    ]
