# Generated by Django 4.2.17 on 2024-12-19 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data', models.DateField()),
                ('hora_abertura', models.TimeField()),
                ('hora_fechamento', models.TimeField()),
                ('status', models.IntegerField(choices=[(0, 'ABERTA'), (1, 'FECHADA')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamentos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('metodo', models.IntegerField(choices=[(0, 'DINHEIRO'), (1, 'CREDITO'), (2, 'DEBITO'), (3, 'PIX')], default=0)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=5)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.contas')),
            ],
        ),
    ]
