# Generated by Django 4.2.17 on 2025-02-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contas',
            name='hora_fechamento',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='contas',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
