# Generated by Django 4.2.17 on 2025-02-12 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_itemadicionais_quantidade_and_more'),
        ('bills', '0003_alter_contas_hora_fechamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contas',
            name='pedido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conta', to='orders.pedidos'),
        ),
    ]
