# Generated by Django 4.2.17 on 2024-12-18 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acompanhamentos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Adicionais',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unidade_medida', models.IntegerField(choices=[(0, 'KILO'), (1, 'LITRO'), (2, 'GRAMA'), (3, 'ML')])),
            ],
        ),
        migrations.CreateModel(
            name='Mesas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'DISPONIVEL'), (1, 'INDISPONIVEL'), (2, 'RESERVADA')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(0, 'NA_FILA'), (1, 'PREPARANDO'), (2, 'PRONTO')], default=0)),
                ('data', models.DateField()),
                ('hora_abertura', models.TimeField()),
                ('hora_fechamento', models.TimeField()),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.funcionarios')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.mesas')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedidos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=5)),
                ('acompanhamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.acompanhamentos')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.pedidos')),
            ],
        ),
        migrations.CreateModel(
            name='ItemAdicionais',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=5)),
                ('adicional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.adicionais')),
                ('item_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.itempedidos')),
            ],
        ),
    ]
