# Generated by Django 4.2.17 on 2025-01-05 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0007_alter_itempratos_prato_alter_itempratos_produto'),
        ('orders', '0005_alter_itempedidos_acompanhamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedidos',
            name='prato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dishes.pratos'),
        ),
    ]
