# Generated by Django 4.2.17 on 2025-01-05 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_itempedidos_prato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedidos',
            name='acompanhamento',
        ),
        migrations.AddField(
            model_name='itempedidos',
            name='acompanhamento',
            field=models.ManyToManyField(null=True, to='orders.acompanhamentos'),
        ),
    ]
