# Generated by Django 4.2.17 on 2025-02-12 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_itempedidos_acompanhamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemadicionais',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemadicionais',
            name='adicional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_adicional', to='orders.adicionais'),
        ),
        migrations.AlterField(
            model_name='itemadicionais',
            name='item_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_adicional', to='orders.itempedidos'),
        ),
        migrations.AlterField(
            model_name='itempedidos',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedido', to='orders.pedidos'),
        ),
    ]
